version: '3.8'

x-common-variables: &common-variables
  NODE_ENV: ${NODE_ENV:-production}

x-database-variables: &database-variables
  POSTGRES_USER: ${DB_USER:-mutumwa_admin}
  POSTGRES_PASSWORD: ${DB_PASSWORD:-mutumwa_secure_pass}
  POSTGRES_DB: ${DB_NAME:-mutumwa_ai}

services:
  postgres:
    image: postgres:15
    container_name: mutumwa-ai-postgres
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    environment:
      <<: *database-variables
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U ${DB_USER:-mutumwa_admin} -d ${DB_NAME:-mutumwa_ai}'
      interval: 5s
      timeout: 20s
      retries: 10
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: mutumwa-ai-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  collector:
    build:
      context: ./collector
      dockerfile: Dockerfile
    container_name: mutumwa-ai-collector
    ports:
      - "${COLLECTOR_PORT:-8888}:8888"
    environment:
      <<: *common-variables
      SERVER_PORT: 8888
      STORAGE_DIR: /app/collector/storage
      HOT_DIR: /app/collector/hotdir
      COLLECTOR_DIR: /app/collector
      REDIS_URL: redis://redis:6379
    volumes:
      - ./collector/storage:/app/collector/storage
      - ./collector/hotdir:/app/collector/hotdir
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: mutumwa-ai-server
    ports:
      - "${SERVER_PORT:-3001}:3001"
    environment:
      <<: *common-variables
      PORT: 3001
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER:-mutumwa_admin}
      DB_PASSWORD: ${DB_PASSWORD:-mutumwa_secure_pass}
      DB_NAME: ${DB_NAME:-mutumwa_ai}
      REDIS_URL: redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mutumwa-ai-frontend
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      <<: *common-variables
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:3001}
    depends_on:
      - server
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: