version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: mutumwa-ai-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mutumwa_ai_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: mutumwa-ai-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  collector:
    build:
      context: ./collector
      dockerfile: Dockerfile
    container_name: mutumwa-ai-collector
    ports:
      - "8888:8888"
    environment:
      - NODE_ENV=production
      - SERVER_PORT=8888
      - STORAGE_DIR=/app/collector/storage
      - HOT_DIR=/app/collector/hotdir
      - COLLECTOR_DIR=/app/collector
    volumes:
      - ./collector/storage:/app/collector/storage
      - ./collector/hotdir:/app/collector/hotdir
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: mutumwa-ai-server
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/mutumwa_ai_dev
      - REDIS_URL=redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mutumwa-ai-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://server:3001
    depends_on:
      - server
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: