name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
      steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Shallow clones should be disabled for better analysis
  docker-compose-validation:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Validate docker-compose.yml
      run: |
        docker-compose config -q

    - name: Check for docker-compose best practices
      run: |
        # Check for version pinning
        if grep -q "latest" docker-compose.yml; then
          echo "Warning: Using 'latest' tag in docker-compose.yml"
        fi
        
        # Check for health checks
        if ! grep -q "healthcheck" docker-compose.yml; then
          echo "Warning: No health checks found in docker-compose.yml"
        fi
